/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cpb.cursos;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@EnableAutoConfiguration
@ComponentScan(basePackages= {"cpb.cursos.controller"})
public class Cursos {
    public static void main(String[] args) {
        SpringApplication.run(Cursos.class, args);
    }

}
